### ISSUE TITLE
Need support on starknet V0.12.3

### ISSUE THREAD

**Issue by ThemisSmile** [software-mansion/starknet.py#1248]
### Feature Request

It seems like the current release does not support starknet version 0.12.3, It turns out error 
`starknet_py.net.client_errors.ClientError: Client failed with code 400: {"code": "StarknetErrorCode.DEPRECATED_ENDPOINT", "message": "Endpoint is deprecated from version 0.12.3."}`
How to adjust the code to fit v0.12.3

**Comment by ddoktorski** [comment]
Hi @ThemisSmile

Thank you for reaching out. The feeder gateway functionality has been deprecated on mainnet recently. This means that the `GatewayClient` will also be removed from the starknet.py in our upcoming release.

We recommend transitioning to use the RPC node and `FullNodeClient`. For more details, please check out our [documentation](https://starknetpy.readthedocs.io/en/latest/).

Since this change is a part of our planned updates, I am going to close this issue for now. However, please don't hesitate to reach out again if you have any further questions or need additional assistance.

**Comment by ThemisSmile** [comment]
> Hi @ThemisSmile
> 
> Thank you for reaching out. The feeder gateway functionality has been deprecated on mainnet recently. This means that the `GatewayClient` will also be removed from the starknet.py in our upcoming release.
> 
> We recommend transitioning to use the RPC node and `FullNodeClient`. For more details, please check out our [documentation](https://starknetpy.readthedocs.io/en/latest/).
> 
> Since this change is a part of our planned updates, I am going to close this issue for now. However, please don't hesitate to reach out again if you have any further questions or need additional assistance.

Thanks, this works for me. I forgot to switch to fullnodeclient
