### ISSUE TITLE
Update docs

### ISSUE THREAD

**Issue by THenry14** [software-mansion/starknet.py#1354]
### Feature Request

eg https://starknetpy.readthedocs.io/en/latest/api/full_node_client.html#starknet_py.net.full_node_client.FullNodeClient.__init__ stated there is net param, which is not the case

**Comment by ddoktorski** [comment]
In the scope of this issue also check that code examples are correctly displayed in the API docs. For example [test_execute](https://github.com/software-mansion/starknet.py/blob/5ba387da76bc2731c3eb7cb81642fd8c0301d118/starknet_py/tests/e2e/docs/code_examples/test_account.py#L28) needs to be renamed to `test_execute_v1` and `docs-start` and `docs-end` should use a name `execute_v1` instead of `execute`
