### ISSUE TITLE
[BUG] RPC declare transaction incorrect field name

### ISSUE THREAD

**Issue by cptartur** [software-mansion/starknet.py#256]
RPC declare transaction should have a `contract_class` field instead of `class_hash`. Additional tests should be added for these types of transactions.

**Comment by drknzz** [comment]
The field `contract_class` instead of `class_hash` in RPC Declare Transaction started out as a bug, since in [RPC 0.15.0 specification](https://github.com/starkware-libs/starknet-specs/blob/606c21e06be92ea1543fd0134b7f98df622c2fbf/api/starknet_api_openrpc.json#L1171) DECLARE_TXN has `contract_class` as a key (instead of `class_hash`).

However since [RPC 0.20.0 specification](https://github.com/starkware-libs/starknet-specs/blob/6f00c4c2bc23f2f18530fbb585b3bc00eab5fb39/api/starknet_api_openrpc.json#L1382) the field changed to `class_hash` and the change is yet to be implemented in devnet.

This [PR](https://github.com/software-mansion/starknet.py/pull/267) introduces tests for Declare Transaction without actually changing current RPC Declare Transaction structure.
