### ISSUE TITLE
[BUG] AccountClient shouldn't have get_code method

### ISSUE THREAD

**Issue by Solpatium** [software-mansion/starknet.py#388]
It is only available for GatewayClient, if AccountClient is provided with RpcClient it will fail.

**Comment by cptartur** [comment]
I agree this method is problematic, however this complicates the usage of `Contract` api with `AccountClient` because `Contract.from_address` uses the `get_code` method. Perhaps a temporary solution would be to raise custom exception if one tries to use `AccountClient.get_code`? Once rpc v0.2.0 is implemented, we'll be able to replace `get_code` by `get_class_by_hash` method.
