### ISSUE TITLE
Investigate crypto-cpp builds on MacOS Ventura

### ISSUE THREAD

**Issue by cptartur** [software-mansion/starknet.py#600]
Wild guess, but it might be a problem with crypto-cpp. MacOS Ventura has bumped the version to 13, and we probably lack compiled version so wheel tried to build from source. Sadly this is something that is at the moment impossible to automate using gh actions. 

It would be great if someone that sports older version of macos could confirm. Alternatively, we can check using gh actions. Meanwhile, I will add it to my list to add compiled version for new system.

_Originally posted by @THenry14 in https://github.com/software-mansion/starknet.py/pull/598#discussion_r1050593147_

**Comment by THenry14** [comment]
At the time of having this issue, fastecdsa indeed needed cmake in order to install on new macos. Since then however, a new version was released containing a needed wheels.

Therefore my recommendation is to inform users (in the docs under mac section - both amd and apple sillicon) that if installation fails, they should install cmake and try again (we could maybe add it to the dev/some other dependencies in the project?)
